Repository wavesplatform/gowaves, pull requests merged in 2021-11, with the labels that each got.

#565 Dependencies bump
  Makefile
  cmd/forkdetector/internal/registry.go
  cmd/retransmitter/retransmit/utils/counter_test.go
  go.mod
  go.sum
  pkg/client/errors_test.go
  pkg/client/types_test.go
  pkg/grpc/generated/waves/amount.pb.go
  pkg/grpc/generated/waves/block.pb.go
  pkg/grpc/generated/waves/invoke_script_result.pb.go
  pkg/grpc/generated/waves/node/grpc/accounts_api.pb.go
  pkg/grpc/generated/waves/node/grpc/assets_api.pb.go
  pkg/grpc/generated/waves/node/grpc/blockchain_api.pb.go
  pkg/grpc/generated/waves/node/grpc/blocks_api.pb.go
  pkg/grpc/generated/waves/node/grpc/transactions_api.pb.go
  pkg/grpc/generated/waves/order.pb.go
  pkg/grpc/generated/waves/recipient.pb.go
  pkg/grpc/generated/waves/transaction.pb.go
  pkg/node/peer_manager/storage/types_test.go
  pkg/p2p/conn/wrap_test.go
  pkg/p2p/peer/peer_test.go
  pkg/ride/meta/generated/DAppMeta.pb.go
  pkg/util/transferv1_test.go
Labels: dependencies

#581 Zero assetID/Digest as waves bugfix
  pkg/grpc/server/transactions_api_test.go
  pkg/proto/protobuf_converters.go
  pkg/proto/types.go
  pkg/ride/converters.go
  pkg/ride/functions_common.go
  pkg/ride/tree_evaluation_test.go
  pkg/state/assets.go
  pkg/state/fee_validation_test.go
  pkg/state/invoke_applier.go
  pkg/state/invoke_applier_test.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_differ_test.go
  pkg/state/transaction_fee_counter.go
Labels: bug

#540 OrderV4 with 'Eip712Signature' protobuf field support.
  cmd/wmd/internal/data/updates.go
  pkg/proto/eth_crypto.go
  pkg/proto/eth_math.go
  pkg/proto/eth_signer.go
  pkg/proto/eth_typed_data.go
  pkg/proto/protobuf_converters.go
  pkg/proto/transactions_test.go
  pkg/proto/transactions_with_proofs.go
  pkg/proto/types.go
  pkg/proto/types_test.go
  pkg/ride/converters.go
  pkg/ride/converters_test.go
  pkg/state/common_test.go
  pkg/state/invoke_applier_test.go
  pkg/state/script_caller.go
  pkg/state/scripts_storage.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_checker_test.go
  pkg/state/transaction_differ.go
  pkg/state/transaction_differ_test.go
  pkg/state/verifier.go
  pkg/util/common/util.go
Labels: awaiting-release

#563 Metamask rpc api
  cmd/node/node.go
  pkg/grpc/server/assets_api_test.go
  pkg/metamask/app.go
  pkg/metamask/metamask.go
  pkg/metamask/metamask_zenrpc.go
  pkg/metamask/middleware.go
  pkg/metamask/server.go
  pkg/metamask/service.go
  pkg/metamask/utils.go
  pkg/miner/scheduler/scheduler.go
  pkg/mock/state.go
  pkg/proto/asset.go
  pkg/proto/transactions.go
  pkg/state/api.go
  pkg/state/errors.go
  pkg/state/eth_info.go
  pkg/state/sponsored_assets_test.go
  pkg/state/state.go
  pkg/state/threadsafe_wrapper.go
  pkg/state/transaction_performer_test.go
  pkg/util/common/util.go
  pkg/util/common/util_test.go
Labels: awaiting-release
