Repository wavesplatform/gowaves, pull requests merged in 2021-12, with the labels that each got.

#600 Fixed issue with incorrect keys during batched storage normalization.
  pkg/state/address_transactions.go
  pkg/state/batched_storage.go
  pkg/state/constants.go
  pkg/state/history_storage.go
  pkg/state/history_storage_test.go
  pkg/state/internal_constants.go
  pkg/state/keys.go
Labels: bug

#601 Fixed bug in 'unpackPayments' function in 'ethabi' package.
  pkg/proto/eth_transaction_test.go
  pkg/proto/ethabi/abi_test.go
  pkg/proto/ethabi/argument.go
  pkg/proto/ethabi/methods_map.go
  pkg/proto/ethabi/parsing_test.go
  pkg/proto/ethabi/unpack.go
Labels: bug

#602 Fix make string types
  pkg/ride/functions_strings.go
  pkg/ride/functions_strings_test.go
Labels: do not merge

#606 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go.yml
  cmd/binclient/main.go
  cmd/convert/main.go
  cmd/custom/node.go
  cmd/forkdetector/internal/api.go
  cmd/forkdetector/internal/registry.go
  cmd/genconfig/genconfig.go
  cmd/genesis/genesis.go
  cmd/node/node.go
  pkg/api/errors/validation.go
  pkg/miner/features.go
  pkg/proto/proto.go
  pkg/proto/protobuf_converters.go
  pkg/util/genesis_generator/gen.go
  pkg/util/genesis_generator/gen_test.go
  pkg/wallet/crypt.go
Labels: enhancement, do not merge

#610 Added case for 'EthereumTransaction' in 'checkTx' function.
  pkg/state/verifier.go
Labels: bug

#612 Vulnerability scanners CI workflows
  .github/workflows/security.yml
  cmd/convert/main.go
  cmd/custom/node.go
  cmd/forkdetector/forkdetector.go
  cmd/forkdetector/internal/queues.go
  cmd/forkdetector/internal/registry.go
  cmd/integration/main.go
  cmd/node/node.go
  cmd/wallet/main.go
  cmd/wmd/internal/data/symbols.go
  cmd/wmd/internal/importer.go
  pkg/client/client.go
  pkg/consensus/blocks_validation.go
  pkg/importer/importer.go
  pkg/keyvalue/bloom_filter.go
  pkg/node/peer_manager/storage/cbor.go
  pkg/node/state_fsm/fsm_halt.go
  pkg/ride/generate/main.go
  pkg/state/address_transactions.go
  pkg/state/assets.go
  pkg/state/blockreadwriter.go
  pkg/state/diff_applier.go
  pkg/state/state.go
  pkg/state/test_util.go
  pkg/wallet/loader.go
Labels: enhancement

#637 Update security.yml
  .github/workflows/security.yml
Labels: enhancement
