Repository wavesplatform/gowaves, pull requests merged in 2022-05, with the labels that each got.

#730 CI workfows update
  .github/workflows/go.yml
  .github/workflows/security.yml
Labels: enhancement

#735 Upload coverage to Codecov only from 'wavesplatform/gowaves' repo
  .github/workflows/go.yml
Labels: enhancement

#736 Fix upload coverage to Codecov only from 'wavesplatform/gowaves' repo
  .github/workflows/go.yml
Labels: bug

#741 Fix ethereum transaction differ
  pkg/metamask/service.go
  pkg/proto/ethabi/methods_map.go
  pkg/proto/ethabi/parsing_test.go
  pkg/proto/types.go
  pkg/ride/converters.go
  pkg/state/script_caller.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_differ.go
  pkg/state/verifier.go
  pkg/state/verifier_test.go
Labels: bug

#734 Security ci semgrep
  .github/workflows/security.yml
  .semgrepignore
  Dockerfile
  cmd/forkdetector/internal/registry.go
  cmd/forkdetector/internal/storage.go
  cmd/forkdetector/internal/synchronizer.go
  cmd/forkdetector/internal/tcpext.go
  cmd/integration/main.go
  cmd/retransmitter/retransmit/httpserver/server.go
  cmd/retransmitter/retransmit/utils/counter.go
  cmd/retransmitter/retransmit/utils/known_peers.go
  cmd/retransmitter/retransmit/utils/known_peers_storage.go
  cmd/wallet/main.go
  cmd/wmd/internal/api.go
  cmd/wmd/internal/state/storage.go
  cmd/wmd/wmd.go
  pkg/api/errors/validation.go
  pkg/api/node_api.go
  pkg/client/client.go
  pkg/client/transactions.go
  pkg/crypto/internal/groth16/bls12381/proof.go
  pkg/crypto/internal/groth16/bls12381/verificationKey.go
  pkg/crypto/internal/groth16/bn256/proof.go
  pkg/crypto/internal/groth16/bn256/verificationKey.go
  pkg/keyvalue/bloom_filter.go
  pkg/keyvalue/leveldb.go
  pkg/libs/ntptime/ntptime.go
  pkg/libs/ntptime/ntptime_test.go
  pkg/libs/serializer/serializer.go
  pkg/metrics/metrics.go
  pkg/node/node.go
  pkg/node/peer_manager/peer_manager.go
  pkg/node/state_fsm/fsm_ng.go
  pkg/p2p/conn/conn.go
  pkg/proto/addresses.go
  pkg/proto/eth_crypto.go
  pkg/proto/eth_signer.go
  pkg/proto/microblock.go
  pkg/proto/proto.go
  pkg/proto/proto_test.go
  pkg/proto/transactions.go
  pkg/proto/types.go
  pkg/ride/compiler.go
  pkg/ride/parserV1.go
  pkg/state/assets.go
  pkg/state/database.go
  pkg/state/keys.go
  pkg/state/monetary_policy.go
  pkg/state/scripts_storage.go
  pkg/state/state.go
  pkg/state/transaction_differ.go
  pkg/util/common/util.go
Labels: enhancement

#743 Fixed bug with estimator version in'stateManager.EstimatorVersion'.
  pkg/state/state.go
Labels: bug

#746 Refactoring of params passing to fee checkers. Correct function costs…
  pkg/proto/transactions_with_proofs.go
  pkg/ride/functions.go
  pkg/ride/generate/main.go
  pkg/state/appender.go
  pkg/state/fee_validation.go
  pkg/state/fee_validation_test.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_checker_test.go
Labels: bug

#750 Ignore jobs in 'security' CI workflow if actor is the dependabot.
  .github/workflows/security.yml
Labels: bug

#753 Fixed bug with asset decimals in 'Eth_Call' ethereum JSON RPC method.
  pkg/metamask/service.go
Labels: bug

#756 Add 'cache' option for 'setup-go' shared action in CI workflows.
  .github/workflows/go.yml
  .github/workflows/security.yml
Labels: enhancement

#757 Update 'gopkg.in/yaml.v3' dependency.
  go.mod
  go.sum
Labels: dependencies, go

#747 Add exclude list for fsm
  cmd/binclient/main.go
  cmd/custom/node.go
  cmd/node/node.go
  pkg/node/messages/skip_message_list.go
  pkg/node/peer_manager/spawner.go
  pkg/node/state_fsm/default_test.go
  pkg/node/state_fsm/fsm.go
  pkg/node/state_fsm/fsm_halt.go
  pkg/node/state_fsm/fsm_idle.go
  pkg/node/state_fsm/fsm_idle_test.go
  pkg/node/state_fsm/fsm_ng.go
  pkg/node/state_fsm/fsm_persist.go
  pkg/node/state_fsm/fsm_sync.go
  pkg/node/state_fsm/fsm_sync_test.go
  pkg/node/state_fsm/fsm_test.go
  pkg/p2p/peer/peer.go
  pkg/proto/microblock.go
  pkg/proto/proto.go
  pkg/services/services.go
Labels: enhancement

#758 Corrected Ethereum transaction type
  pkg/proto/eth_signer.go
  pkg/proto/eth_transaction.go
  pkg/proto/eth_transaction_test.go
  pkg/proto/transactions.go
Labels: bug

#751 Eliminate script parsing in wrapped state
  pkg/metamask/service.go
  pkg/mock/state.go
  pkg/ride/environment.go
  pkg/ride/functions_invocations.go
  pkg/ride/functions_proto.go
  pkg/ride/functions_proto_test.go
  pkg/ride/smart_state_moq_test.go
  pkg/ride/tree_evaluation_test.go
  pkg/state/api.go
  pkg/state/scripts_storage.go
  pkg/state/scripts_storage_interface.go
  pkg/state/scripts_storage_moq_test.go
  pkg/state/smart_state_moq_test.go
  pkg/state/state.go
  pkg/state/threadsafe_wrapper.go
  pkg/types/types.go
Labels: enhancement
