Repository wavesplatform/gowaves, pull requests merged in 2022-07, with the labels that each got.

#798 Add ride v6 native functions
  pkg/ride/functions.go
  pkg/ride/generate/main.go
Labels: bug, do not merge

#797 Fix available balance in wrapped state
  pkg/ride/diff_state.go
  pkg/ride/environment.go
  pkg/ride/functions.go
  pkg/ride/generate/main.go
  pkg/ride/smart_state_moq_test.go
  pkg/ride/tree_evaluation_test.go
  pkg/state/smart_state_moq_test.go
  pkg/state/state.go
  pkg/types/types.go
  pkg/util/common/util_test.go
Labels: bug

#800 Correct complexity calculator selection for scripts of Ride versions …
  pkg/ride/environment.go
  pkg/ride/functions_proto.go
  pkg/ride/tree_evaluation_test.go
  pkg/state/appender.go
  pkg/state/invoke_applier.go
  pkg/state/script_caller.go
Labels: bug

#801 Updated costs of make string and split string functions for Ride V6
  pkg/ride/functions.go
  pkg/ride/functions_strings.go
  pkg/ride/functions_strings_test.go
  pkg/ride/generate/main.go
Labels: bug

#804 Spoil actions count validation of v6 scripts with rules from old ver…
  pkg/ride/environment.go
  pkg/ride/tree_evaluation_test.go
Labels: bug

#814 Add lease canceler check to wrapped state
  pkg/ride/environment.go
  pkg/ride/tree_evaluation_test.go
Labels: bug

#822 Fix actions counting
  pkg/proto/actions_validator.go
  pkg/ride/environment.go
  pkg/ride/tree_evaluation_test.go
Labels: bug

#823 Euclidean division of BigInts replaced by truncated division
  pkg/ride/functions_bigint.go
  pkg/ride/functions_bigint_test.go
Labels: bug

#828 Fail cheap invokes on actions validation before specified heigh
  pkg/settings/embedded/stagenet.json
  pkg/state/invoke_applier.go
  pkg/state/invoke_applier_test.go
Labels: bug

#816 Fix eth call responses
  pkg/metamask/service.go
  pkg/metamask/service_test.go
Labels: bug

#829 Client '/addresses/data/' endpoints with tests
  pkg/client/addresses.go
  pkg/client/addresses_test.go
Labels: enhancement

#811 Fixed lease cancel
  pkg/ride/diff_state.go
  pkg/ride/environment.go
  pkg/ride/tree_evaluation_test.go
Labels: bug

#807 Scripts storage enhancement
  pkg/ride/environment.go
  pkg/ride/smart_state_moq_test.go
  pkg/ride/tree_evaluation_test.go
  pkg/state/constants.go
  pkg/state/ethereum_tx_test.go
  pkg/state/invoke_applier.go
  pkg/state/scripts_storage.go
  pkg/state/scripts_storage_interface.go
  pkg/state/scripts_storage_moq_test.go
  pkg/state/scripts_storage_test.go
  pkg/state/smart_state_moq_test.go
  pkg/state/state.go
  pkg/types/types.go
Labels: enhancement, wip
