Repository wavesplatform/gowaves, pull requests merged in 2022-06, with the labels that each got.

#755 Check on in-memory mapping of account on it's number added. Check on …
  pkg/state/accounts_data_storage.go
  pkg/state/accounts_data_storage_test.go
  pkg/state/common_test.go
  pkg/state/state.go
Labels: bug

#769 Bump go dependency 'github.com/syndtr/goleveldb'.
  go.mod
  go.sum
Labels: dependencies, go

#771 Update 'Dockerfile'.
  Dockerfile
Labels: dependencies, docker

#773 update protocol version to 1.4
  cmd/node/node.go
Labels: do not merge, awaiting-release

#778 Script size limit increased to 160KB for DApps after RideV6 activatio…
  pkg/proto/transactions.go
  pkg/proto/transactions_with_proofs.go
  pkg/state/fee_validation.go
  pkg/state/testdata/scripts/ride5_dapp_exceeds_32kb.base64
  pkg/state/transaction_checker.go
  pkg/state/transaction_checker_test.go
Labels: bug

#780 Pass correct parameter to the 'NewEnvironmentWithWrappedState'.
  pkg/state/script_caller.go
Labels: bug

#794 Add 'NewDataEntryFromJSON' helper function.
  pkg/proto/types.go
  pkg/proto/types_test.go
Labels: enhancement

#793 Handle Delete data entry correctly
  pkg/proto/types.go
  pkg/state/accounts_data_storage.go
Labels: bug
