Repository wavesplatform/gowaves, pull requests merged in 2022-11, with the labels that each got.

#929 Fixed data types in 'LeaseAction' struct in 'pkg/client'.
  pkg/client/state_changes.go
Labels: bug

#934 Migrate to 'github.com/btcsuite/btcd/btcec/v2'.
  go.mod
  go.sum
  pkg/crypto/ecdsa.go
  pkg/crypto/ecdsa_test.go
  pkg/proto/eth_crypto.go
  pkg/proto/eth_signer.go
  pkg/proto/types.go
  pkg/ride/converters_test.go
  pkg/state/common_test.go
Labels: enhancement

#928 Fix payments and balances validation order
  pkg/proto/actions_validator.go
  pkg/ride/diff_state.go
  pkg/ride/environment.go
  pkg/ride/functions_proto.go
  pkg/ride/test_helpers_test.go
  pkg/ride/tree_evaluation_test.go
Labels: bug

#938 Evaluation complexity of messageless throw function changed back to 2.
  pkg/ride/functions.gen.go
  pkg/ride/generate/internal/functions_generation.go
  pkg/ride/tree_evaluation_test.go
  pkg/ride/tree_evaluator.go
Labels: bug

#937 Fix create alias tx HTTP client broadcast
  pkg/grpc/server/common_test.go
  pkg/proto/transactions_test.go
  pkg/proto/transactions_with_proofs.go
  pkg/proto/transactions_with_sig.go
Labels: bug

#939 Enable grpc server reflection.
  pkg/grpc/server/common_test.go
  pkg/grpc/server/grpc_server.go
  pkg/grpc/server/transactions_api_test.go
Labels: enhancement

#941 Return full address bytes in 'AccountsApiServer.ResolveAlias' gRPC API.
  pkg/grpc/server/accounts_api.go
  pkg/grpc/server/accounts_api_test.go
Labels: bug

#949 Fixed 'Arguments.UnmarshalJSON' method.
  pkg/client/transactions_info_test.go
  pkg/proto/types.go
Labels: bug

#944 Refactor eth crypto
  pkg/proto/eth_access_list_tx.go
  pkg/proto/eth_crypto.go
  pkg/proto/eth_dynamic_fee_tx.go
  pkg/proto/eth_legacy_tx.go
  pkg/proto/eth_signer.go
  pkg/proto/eth_utils.go
  pkg/proto/types.go
  pkg/proto/types_test.go
Labels: refactoring

#946 move callee dapp version check in invoke() to the beginning
  pkg/ride/functions_invocations.go
  pkg/ride/functions_proto.go
  pkg/ride/tree_evaluation_test.go
Labels: refactoring

#952 Fixed the way how blockchain lag is calculated in miner.
  Makefile
  pkg/miner/scheduler/scheduler.go
Labels: bug
