Repository wavesplatform/gowaves, pull requests merged in 2022-10, with the labels that each got.

#885 Add blacklisting
  itests/config/config.go
  pkg/api/app_peers.go
  pkg/api/app_peers_test.go
  pkg/api/node_api.go
  pkg/api/routes.go
  pkg/mock/peer_manager.go
  pkg/mock/peer_storage.go
  pkg/node/peer_manager/peer_manager.go
  pkg/node/peer_manager/peer_storage.go
  pkg/node/peer_manager/peer_storage_test.go
  pkg/node/peer_manager/storage/cbor.go
  pkg/node/peer_manager/storage/cbor_test.go
  pkg/node/peer_manager/storage/types.go
  pkg/node/peer_manager/storage/types_test.go
  pkg/node/state_fsm/fsm_common.go
  pkg/node/state_fsm/fsm_idle.go
  pkg/node/state_fsm/fsm_ng.go
  pkg/node/state_fsm/fsm_sync.go
  pkg/util/common/util.go
  pkg/util/common/util_test.go
Labels: do not merge

#900 Add 'EthereumMetamaskTransaction' to 'ProtobufTransactionsVersions' map.
  pkg/proto/transactions.go
Labels: bug

#902 Add 'enable-metamask-log' command line argument for node.
  cmd/node/node.go
Labels: enhancement

#908 Bump github.com/umbracle/fastrlp to 0.1.0
  go.mod
  go.sum
Labels: dependencies, go

#909 Fix binary argument type marshaling
  pkg/proto/transactions_test.go
  pkg/proto/types.go
  pkg/proto/types_test.go
Labels: bug

#914 Fixed 'Eth_EstimateGas' method for ethereum invoke tx.
  pkg/api/metamask/service.go
Labels: bug

#913 Fixed and refactored 'EthereumTransaction' and smart assets fee validation.
  pkg/proto/eth_transaction.go
  pkg/state/appender.go
  pkg/state/common_test.go
  pkg/state/ethereum_tx_test.go
  pkg/state/fee_validation.go
  pkg/state/transaction_checker.go
Labels: bug

#916 Bump indirect golang.org/x/text from 0.3.7 to 0.3.8
  go.mod
  go.sum
Labels: dependencies, go

#917 Add hex string representation for 'crypto.Digest'.
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
Labels: enhancement

#919 HTTP API '/blocks/headers/' endpoints
  pkg/api/app_blocks.go
  pkg/api/node_api.go
  pkg/api/routes.go
Labels: enhancement

#921 Fix eth invoke zero payments
  pkg/settings/blockchain_settings.go
  pkg/settings/embedded/mainnet.json
  pkg/settings/embedded/stagenet.json
  pkg/settings/embedded/testnet.json
  pkg/state/script_caller.go
  pkg/state/transaction_checker.go
Labels: bug

#924 Fixed BitInt Modulo function
  pkg/proto/addresses_test.go
  pkg/ride/functions_bigint.go
  pkg/ride/functions_bigint_test.go
Labels: bug
