Repository wavesplatform/gowaves, pull requests merged in 2023-03, with the labels that each got.

#1037 Remove stale client methods
  pkg/client/addresses.go
  pkg/client/addresses_test.go
  pkg/client/alias.go
  pkg/client/alias_test.go
  pkg/client/assets.go
  pkg/client/assets_test.go
  pkg/client/blocks.go
  pkg/client/blocks_test.go
  pkg/client/client.go
  pkg/client/consensus.go
  pkg/client/consensus_integration_test.go
  pkg/client/consensus_test.go
  pkg/client/debug.go
  pkg/client/debug_test.go
  pkg/client/peers_integration_test.go
  pkg/client/transactions_integration_test.go
  pkg/client/types.go
  pkg/client/types_test.go
  pkg/client/utils.go
  pkg/client/utils_integration_test.go
  pkg/client/utils_test.go
  pkg/client/wallet.go
  pkg/proto/addresses.go
Labels: refactoring

#1039 Fixed check function for scripts version before V3.
  pkg/ride/environment.go
  pkg/ride/functions_bytes_test.go
  pkg/ride/functions_proto_test.go
  pkg/ride/test_helpers_test.go
  pkg/ride/vm_test.go
Labels: bug

#1047 Version of runc updated to 1.1.5
  Makefile
  go.mod
  go.sum
Labels: dependencies
