Repository wavesplatform/gowaves, pull requests merged in 2023-01, with the labels that each got.

#995 Remove unused packages in 'pkg/util'.
  pkg/node/blocks_applier/node_mocks.go
  pkg/state/state.go
  pkg/state/state_test.go
  pkg/util/byte_helpers/transactions.go
  pkg/util/byte_helpers/transferv1.go
  pkg/util/byte_helpers/transferv1_test.go
  pkg/util/java_opts/parser.go
  pkg/util/lock/rwlock.go
  pkg/util/lock/rwlock_test.go
Labels: refactoring

#997 Fix validation of amount+fee sum in transfer tx.
  pkg/proto/transactions.go
  pkg/proto/transactions_test.go
Labels: bug

#1004 Recipient struct refactoring
  cmd/wmd/internal/data/updates.go
  pkg/api/metamask/service.go
  pkg/grpc/server/transactions_api_test.go
  pkg/grpc/server/tx_filter.go
  pkg/proto/actions_validator.go
  pkg/proto/addresses.go
  pkg/proto/addresses_test.go
  pkg/proto/scripting.go
  pkg/proto/scripting_test.go
  pkg/proto/transactions.go
  pkg/proto/transactions_test.go
  pkg/proto/transactions_with_proofs.go
  pkg/proto/transactions_with_sig.go
  pkg/ride/converters.go
  pkg/ride/diff_state_test.go
  pkg/ride/environment.go
  pkg/ride/functions_proto.go
  pkg/ride/functions_proto_test.go
  pkg/ride/test_helpers_test.go
  pkg/ride/tree_evaluation_test.go
  pkg/state/invoke_applier.go
  pkg/state/invoke_applier_test.go
  pkg/state/state.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_differ.go
  pkg/state/transaction_performer.go
  pkg/state/transaction_performer_test.go
Labels: refactoring

#1003 Added new fields to debug/statehash/<height> API. Added new method debug/statehash/last
  itests/config/config.go
  pkg/api/node_api.go
  pkg/api/routes.go
  pkg/client/debug.go
  pkg/proto/types.go
  pkg/proto/types_test.go
Labels: enhancement
