Repository wavesplatform/gowaves, pull requests merged in 2023-02, with the labels that each got.

#1012 gRPC addresses fix
  itests/node_client/grpc_client.go
  itests/utilities/common_tx_utility.go
  pkg/grpc/server/accounts_api.go
  pkg/grpc/server/accounts_api_test.go
  pkg/proto/scripting.go
Labels: bug

#1022 Added size check on marshaling of byte slice with size.
  pkg/proto/common.go
  pkg/proto/transactions.go
  pkg/proto/transactions_with_proofs.go
  pkg/proto/types.go
Labels: bug

#1028 Bump golang.org/x/net from 0.5.0 to 0.7.0
  go.mod
  go.sum
Labels: dependencies, go

#1029 Update Go version to 1.19
  .github/workflows/go.yml
  .github/workflows/security.yml
  README.md
  go.mod
Labels: enhancement

#1030 Reduced matrix for 'lint' CI job.
  .github/workflows/go.yml
Labels: github_actions

#1031 Update 'golangci-lint' to version 1.51.2
  .github/workflows/go.yml
Labels: github_actions

#1021 Fix ride bytes size checks
  pkg/proto/common.go
  pkg/ride/environment.go
  pkg/ride/functions_bytes.go
  pkg/ride/functions_bytes_test.go
  pkg/ride/functions_proto_test.go
  pkg/ride/functions_strings.go
Labels: bug
