Repository wavesplatform/gowaves, pull requests merged in 2023-12, with the labels that each got.

#1274 Fix 'transferTransactionById' in Ride.
  pkg/api/metamask/service.go
  pkg/proto/eth_transaction.go
  pkg/proto/eth_tx_kind_resolver.go
  pkg/ride/functions_proto.go
Labels: bug

#1140 Add attachment field in order
  pkg/proto/protobuf_converters.go
  pkg/proto/transactions.go
  pkg/proto/transactions_test.go
  pkg/proto/types.go
  pkg/proto/types_test.go
  pkg/ride/ast/attributes.go
  pkg/ride/compiler/ast_parser.go
  pkg/ride/compiler/ast_parser_test.go
  pkg/ride/compiler/stdlib/ride_objects.json
  pkg/ride/constructors.gen.go
  pkg/ride/converters.go
  pkg/ride/converters_test.go
  pkg/ride/environment.go
  pkg/ride/functions.gen.go
  pkg/ride/functions_proto.go
  pkg/ride/objects.gen.go
  pkg/ride/runtime.go
  pkg/ride/runtime_moq_test.go
  pkg/ride/runtime_test.go
  pkg/ride/test_helpers_test.go
  pkg/ride/tree_evaluation_test.go
  pkg/ride/vm_test.go
  pkg/state/appender.go
  pkg/state/invoke_applier.go
  pkg/state/script_caller.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_differ_test.go
Labels: do not merge, awaiting-release

#1257 Ride function replaceByIndex implemented and tested.
  pkg/ride/functions.gen.go
  pkg/ride/functions_list.go
  pkg/ride/functions_list_test.go
  pkg/ride/generate/internal/functions_generation.go
Labels: do not merge, awaiting-release

#1259 CalculateDelay Ride function implemented and partially tested.
  pkg/consensus/pos_calculator.go
  pkg/ride/compiler/stdlib/funcs.json
  pkg/ride/functions.gen.go
  pkg/ride/functions_proto.go
  pkg/ride/functions_proto_test.go
  pkg/ride/generate/internal/functions_generation.go
Labels: do not merge, awaiting-release

#1264 Tests on correct scopes handling by estimator and evaluator added.
  pkg/ride/compiler/ast_parser.go
  pkg/ride/compiler/ast_parser_test.go
  pkg/ride/compiler/stdlib/types.go
  pkg/ride/tree_estimation_test.go
  pkg/ride/tree_evaluation_test.go
Labels: awaiting-release

#1278 Ride v8 disable ride v1 v3 installation
  pkg/state/transaction_checker.go
  pkg/state/transaction_checker_test.go
Labels: awaiting-release

#1281 Create 'ITests' workflow for intergration tests
  .github/workflows/go.yml
  .github/workflows/itests.yml
Labels: github_actions

#1292 Fix lease id calcualtion in ride
  pkg/ride/converters.go
  pkg/ride/converters_test.go
Labels: bug
