Repository wavesplatform/gowaves, pull requests merged in 2023-07, with the labels that each got.

#1144 Tx checker refactoring
  pkg/state/appender.go
  pkg/state/fee_validation_test.go
  pkg/state/invoke_applier.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_checker_test.go
  pkg/state/transaction_handler.go
  pkg/state/transaction_performer.go
  pkg/state/transaction_performer_test.go
Labels: refactoring

#1147 Fixed bug in 'ethereumTransactionToObject' with empty eth tx kind.
  pkg/api/metamask/service.go
  pkg/proto/eth_transaction.go
  pkg/proto/eth_tx_kind_resolver.go
  pkg/proto/eth_utils.go
  pkg/proto/info.go
  pkg/ride/converters.go
  pkg/ride/converters_test.go
  pkg/ride/diff_state.go
  pkg/ride/environment.go
  pkg/ride/functions_proto.go
  pkg/ride/runtime_test.go
  pkg/ride/smart_state_moq_test.go
  pkg/ride/test_helpers_test.go
  pkg/ride/tree_evaluation_test.go
  pkg/state/appender.go
  pkg/state/ethereum_tx_test.go
  pkg/state/smart_state_moq_test.go
  pkg/state/state.go
  pkg/state/transaction_differ.go
  pkg/types/types.go
Labels: bug

#1154 Initialized 'applicationResult.checkerData' for invoke transactions.
  pkg/state/appender.go
  pkg/state/fee_validation_test.go
  pkg/state/invoke_applier.go
  pkg/state/transaction_performer.go
  pkg/state/transaction_performer_test.go
Labels: bug

#1162 Replaced current recording to storage to snapshot applier
  pkg/state/appender.go
  pkg/state/fee_validation_test.go
  pkg/state/snapshot_applier.go
  pkg/state/snapshot_generator.go
  pkg/state/snapshot_generator_test.go
  pkg/state/snapshot_types.go
  pkg/state/state.go
  pkg/state/transaction_checker_test.go
  pkg/state/transaction_differ_test.go
  pkg/state/transaction_handler.go
  pkg/state/transaction_performer.go
  pkg/state/transaction_performer_test.go
Labels: wip

#1167 Use original estimated verifier complexity for accounts with verifier.
  pkg/state/fee_validation.go
  pkg/state/invoke_applier.go
  pkg/state/scripts_complexity.go
Labels: bug
