Repository wavesplatform/gowaves, pull requests merged in 2023-06, with the labels that each got.

#1111 Fixed behaviour of Ride function blockInfoByHeight for non-positive h…
  Makefile
  pkg/proto/info.go
  pkg/ride/converters.go
  pkg/ride/environment.go
  pkg/ride/functions_proto.go
  pkg/ride/functions_proto_test.go
  pkg/ride/runtime_test.go
  pkg/ride/smart_state_moq_test.go
  pkg/ride/test_helpers_test.go
  pkg/ride/tree_evaluation_test.go
  pkg/state/appender.go
  pkg/state/common_test.go
  pkg/state/script_caller.go
  pkg/state/smart_state_moq_test.go
  pkg/state/state.go
  pkg/state/transaction_differ.go
  pkg/types/types.go
Labels: bug

#1123 Pass correct block height when counting block reward votes.
  pkg/state/state.go
Labels: bug

#1122 Bump golang from 1.20.4-alpine3.16 to 1.20.5-alpine3.18
  Dockerfile.gowaves-it
Labels: dependencies, docker

#1136 Fixed check for 'OrderV3' feature for exchange tx.
  pkg/state/transaction_checker.go
Labels: bug

#1141 Refactor cancel leases to disabled aliases
  pkg/state/aliases.go
  pkg/state/exclusions.go
  pkg/state/invoke_applier.go
  pkg/state/keys.go
  pkg/state/leases.go
  pkg/state/state.go
  pkg/state/transaction_performer.go
Labels: refactoring

#1145 Snapshot applier
  pkg/state/balances.go
  pkg/state/balances_test.go
  pkg/state/diff_applier.go
  pkg/state/keys.go
  pkg/state/leases.go
  pkg/state/orders_volume.go
  pkg/state/orders_volume_test.go
  pkg/state/scripts_complexity.go
  pkg/state/snapshot_applier.go
  pkg/state/state.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_differ.go
  pkg/state/transaction_performer.go
  pkg/state/transaction_performer_test.go
Labels: wip, do not merge

#1078 Node transaction snapshots
  pkg/state/appender.go
  pkg/state/block_differ.go
  pkg/state/block_differ_test.go
  pkg/state/fee_validation_test.go
  pkg/state/invoke_applier.go
  pkg/state/invoke_applier_test.go
  pkg/state/transaction_checker_test.go
  pkg/state/transaction_differ_test.go
  pkg/state/transaction_handler.go
  pkg/state/transaction_performer.go
  pkg/state/transaction_performer_snapshots.go
  pkg/state/transaction_performer_test.go
  pkg/state/transaction_snapshot_test.go
Labels: wip
