Repository wavesplatform/gowaves, pull requests merged in 2024-08, with the labels that each got.

#1460 Improve `importer` utility with buffered reading
  pkg/importer/blocks_importer.go
  pkg/importer/blocks_reader.go
  pkg/importer/importer.go
  pkg/importer/snapshots_importer.go
  pkg/importer/snapshots_reader.go
Labels: enhancement

#1461 Add `disable-bloom` flag for utilities
  cmd/importer/importer.go
  cmd/rollback/main.go
  cmd/statehash/statehash.go
Labels: enhancement

#1464 Moved to Go 1.22
  .github/workflows/codeql-analysis.yml
  .github/workflows/go.yml
  .github/workflows/itests.yml
  .github/workflows/itests_race.yml
  .github/workflows/security.yml
  README.md
  go.mod
Labels: go

#1463 Bump github.com/ory/dockertest/v3 from 3.10.0 to 3.11.0
  go.mod
  go.sum
Labels: dependencies, go

#1474 Create 'EnrichedSmartState' interface.
  pkg/ride/diff_state.go
  pkg/ride/environment.go
  pkg/state/appender.go
  pkg/state/ethereum_tx_test.go
  pkg/state/script_caller.go
  pkg/state/smart_state_moq_test.go
  pkg/types/types.go
Labels: refactoring

#1477 Added work-around to handle the Docker configuration issue
  Dockerfile.gowaves-it
  itests/docker/docker.go
Labels: bug, docker
