Repository wavesplatform/gowaves, pull requests merged in 2024-01, with the labels that each got.

#1296 New test cases added to Lease Action ID generation test.
  pkg/proto/scripting_test.go
Labels: enhancement

#1255 Ride V8 library version added. Tests updated.
  pkg/consensus/pos_calculator.go
  pkg/proto/protobuf_converters.go
  pkg/proto/transactions.go
  pkg/proto/transactions_test.go
  pkg/proto/types.go
  pkg/proto/types_test.go
  pkg/ride/ast/attributes.go
  pkg/ride/compiler/ast_parser.go
  pkg/ride/compiler/ast_parser_test.go
  pkg/ride/compiler/stdlib/funcs.json
  pkg/ride/compiler/stdlib/ride_objects.json
  pkg/ride/compiler/stdlib/structs.go
  pkg/ride/compiler/stdlib/types.go
  pkg/ride/compiler/stdlib/vars.json
  pkg/ride/constants.gen.go
  pkg/ride/constraints.go
  pkg/ride/constructors.gen.go
  pkg/ride/converters.go
  pkg/ride/converters_test.go
  pkg/ride/environment.go
  pkg/ride/functions.gen.go
  pkg/ride/functions_list.go
  pkg/ride/functions_list_test.go
  pkg/ride/functions_proto.go
  pkg/ride/functions_proto_test.go
  pkg/ride/generate/internal/constants_generation.go
  pkg/ride/generate/internal/functions_generation.go
  pkg/ride/objects.gen.go
  pkg/ride/runtime.go
  pkg/ride/runtime_moq_test.go
  pkg/ride/runtime_test.go
  pkg/ride/selectors.go
  pkg/ride/test_helpers_test.go
  pkg/ride/tree_estimation_test.go
  pkg/ride/tree_estimatorV1.go
  pkg/ride/tree_estimatorV2.go
  pkg/ride/tree_estimatorV3.go
  pkg/ride/tree_estimatorV4.go
  pkg/ride/tree_evaluation_test.go
  pkg/ride/tree_evaluator.go
  pkg/ride/vm_test.go
  pkg/state/appender.go
  pkg/state/invoke_applier.go
  pkg/state/script_caller.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_checker_test.go
  pkg/state/transaction_differ_test.go
Labels: do not merge, awaiting-release

#1299 Validate header before applying after features activation stage.
  pkg/consensus/blocks_validation.go
  pkg/state/state.go
Labels: bug

#1303 Run 'state' package long tests in parallel.
  pkg/state/batched_storage_test.go
  pkg/state/blockreadwriter_test.go
Labels: enhancement

#1309 Don't log empty errors in integration tests.
  itests/utilities/common.go
Labels: enhancement
