Repository wavesplatform/gowaves, pull requests merged in 2024-04, with the labels that each got.

#1371 Fix snapshot generation for reissue tx.
  pkg/settings/blockchain_settings.go
  pkg/state/snapshot_generator.go
  pkg/state/transaction_checker.go
Labels: bug

#1376 Bump golang.org/x/net from 0.21.0 to 0.23.0
  .github/workflows/security.yml
  go.mod
  go.sum
Labels: dependencies, go

#1377 Handle interrupt signal and blokchain file EOF.
  cmd/importer/importer.go
  pkg/importer/importer.go
  pkg/state/state_test.go
Labels: enhancement

#1070 CPU profile of importer added as importer.pgo file.
  .gitattributes
  Makefile
  importer.pgo
Labels: enhancement

#1387 Fix size checks for snapshots importer.
  pkg/importer/importer.go
  pkg/importer/snapshots_reader.go
  pkg/proto/block_snapshot.go
Labels: bug

#1388 Fix 'newBlocks.current' getter for binary blocks.
  pkg/state/state.go
Labels: bug
