Repository wavesplatform/gowaves, pull requests merged in 2024-06, with the labels that each got.

#1427 Use go version '1.21.x' in security workflow.
  .github/workflows/security.yml
Labels: github_actions

#1420 Convert utility rework. Option to sign transactions added.
  Makefile
  cmd/convert/README.md
  cmd/convert/config.go
  cmd/convert/main.go
Labels: enhancement

#1411 Fix wallet's 'show' option.
  cmd/wallet/main.go
Labels: bug

#1435 Fix block rewards calculator.
  pkg/state/rewards_calculator.go
  pkg/state/rewards_calculator_test.go
Labels: bug
