Repository wavesplatform/gowaves, pull requests merged in 2024-02, with the labels that each got.

#1314 Adding block height reduced by 1 for UTX transactions validation.
  pkg/miner/micro_miner.go
  pkg/state/appender.go
Labels: bug

#1316 Data race while accessing current peer fixed.
  pkg/node/network/network.go
Labels: bug

#1313 Fix 'no-connections' flag for the 'node'.
  cmd/node/node.go
Labels: bug

#1322 Bump golang from 1.21.7-alpine3.18 to 1.22.0-alpine3.19
  Dockerfile.gowaves-it
Labels: dependencies, docker

#1321 Add block snapshot http route
  pkg/api/blocks_test.go
  pkg/api/node_api.go
  pkg/api/routes.go
  pkg/proto/addresses.go
  pkg/proto/block_snapshot.go
  pkg/proto/block_snapshot_test.go
  pkg/proto/snapshot_types.go
  pkg/proto/types.go
  pkg/state/scripts_complexity.go
  pkg/state/snapshot_applier.go
  pkg/state/snapshot_generator.go
  pkg/state/snapshot_generator_internal_test.go
  pkg/state/snapshot_hasher.go
Labels: enhancement

#1323 Trivial mutex protection implemented.
  pkg/state/features.go
Labels: bug

#1324 Bump golangci/golangci-lint-action from v2 to v3
  .github/workflows/go.yml
Labels: dependencies, github_actions

#1325 Moved to Go 1.21
  .github/workflows/go.yml
  .github/workflows/itests.yml
  .github/workflows/security.yml
  README.md
  go.mod
  go.sum
Labels: go

#1326 Script result internal snapshot
  pkg/state/appender.go
  pkg/state/block_differ_test.go
  pkg/state/ethereum_tx_test.go
  pkg/state/internal_snapshots_types.go
  pkg/state/invoke_applier.go
  pkg/state/snapshot_applier.go
  pkg/state/snapshot_generator.go
  pkg/state/snapshot_generator_internal_test.go
  pkg/state/transaction_checker_test.go
  pkg/state/transaction_handler.go
  pkg/state/transaction_performer.go
  pkg/state/transaction_performer_test.go
Labels: refactoring

#1328 Use correct height for sponsorhip feature activation check
  pkg/state/sponsored_assets.go
Labels: bug

#1334 Fix 'big.Int' bytes representation in snapshot hasher
  pkg/ride/functions_bigint.go
  pkg/ride/functions_bigint_test.go
  pkg/state/snapshot_hasher.go
  pkg/state/snapshot_hasher_internal_test.go
  pkg/util/common/util.go
  pkg/util/common/util_test.go
Labels: bug

#1333 Fix 'isNFT' flag initialization for assets
  pkg/state/assets.go
  pkg/state/assets_test.go
  pkg/state/balances.go
  pkg/state/balances_test.go
  pkg/state/common_test.go
  pkg/state/constants.go
  pkg/state/ethereum_tx_test.go
  pkg/state/fee_validation.go
  pkg/state/invoke_applier.go
  pkg/state/snapshot_applier.go
  pkg/state/snapshot_generator.go
  pkg/state/snapshot_generator_internal_test.go
  pkg/state/state.go
  pkg/state/transaction_checker.go
  pkg/state/transaction_checker_test.go
  pkg/state/transaction_differ.go
  pkg/state/transaction_performer_test.go
Labels: bug

#1337 Support block snapshot hash in 'statehash' utility
  cmd/statehash/statehash.go
Labels: enhancement

#1341 Fix light node fee distribution
  pkg/state/appender.go
  pkg/state/snapshot_generator_internal_test.go
  pkg/state/state.go
Labels: do not merge

#1345 Add setup-go step for 'CodeQL' CI workflow.
  .github/workflows/codeql-analysis.yml
Labels: github_actions

#1349 Handle new 'StateHash' field for 'MicroBlock' signature.
  pkg/proto/microblock.go
  pkg/proto/microblock_test.go
Labels: bug
