Repository wavesplatform/gowaves, pull requests merged in 2024-10, with the labels that each got.

#1508 Fix 'TransactionStatus' JSON value for failed status.
  pkg/proto/block_snapshot_test.go
  pkg/proto/types.go
Labels: bug

#1517 Fix challenged blocks handling.
  pkg/consensus/blocks_validation.go
  pkg/consensus/validator_moq_test.go
  pkg/state/balances.go
  pkg/state/balances_test.go
  pkg/state/constants.go
  pkg/state/history_storage.go
  pkg/state/keys.go
  pkg/state/state.go
  pkg/state/state_test.go
Labels: bug

#1519 Update ride generating balance during tx after light node feature
  pkg/ride/diff_state.go
  pkg/ride/environment.go
  pkg/ride/test_helpers_test.go
  pkg/ride/tree_evaluation_test.go
Labels: bug

#1523 Close state resources in case of initializatino failure
  Makefile
  pkg/state/address_transactions.go
  pkg/state/blockreadwriter.go
  pkg/state/common_test.go
  pkg/state/history_formatter.go
  pkg/state/history_formatter_test.go
  pkg/state/history_storage.go
  pkg/state/local_history_storage.go
  pkg/state/local_history_storage_test.go
  pkg/state/state.go
Labels: refactoring

#1522 Add concurrency settings for CI workflows.
  .github/workflows/codeql-analysis.yml
  .github/workflows/go.yml
  .github/workflows/itests.yml
  .github/workflows/security.yml
Labels: enhancement, github_actions

#1527 Remove 'pkg/libs/runner' package.
  cmd/node/node.go
  pkg/api/node.go
  pkg/api/node_api.go
  pkg/api/routes.go
  pkg/libs/runner/asynchronous.go
  pkg/libs/runner/asynchronous_test.go
  pkg/libs/runner/interface.go
  pkg/libs/runner/loggable.go
  pkg/libs/runner/loggable_test.go
  pkg/libs/runner/synchronous.go
  pkg/libs/runner/synchronous_test.go
  pkg/node/node.go
  pkg/services/services.go
Labels: refactoring

#1528 Node return non zero error code if error occurred
  cmd/node/node.go
  pkg/api/node_api.go
  pkg/miner/features.go
  pkg/miner/features_test.go
  pkg/mock/peer_manager.go
  pkg/node/fsm/halt_state.go
  pkg/node/node.go
  pkg/node/peers/peer_manager.go
Labels: enhancement, refactoring

#1525 Flag to validate transactions after deserialization added to convert …
  cmd/convert/config.go
  cmd/convert/main.go
Labels: enhancement
