Repository wavesplatform/gowaves, pull requests merged in 2024-12, with the labels that each got.

#1552 Prepare timers for go1.23.
  pkg/api/app.go
  pkg/api/metamask/service.go
  pkg/libs/ntptime/ntptime.go
  pkg/node/fsm/tasks/tasks.go
  pkg/node/node.go
  pkg/util/limit_listener/listen.go
Labels: refactoring

#1551 Peer address parsing refactoring
  cmd/node/node.go
  pkg/proto/proto.go
  pkg/proto/proto_test.go
Labels: bug, enhancement, refactoring

#1564 CI: set up go after code checkout.
  .github/workflows/go.yml
  .github/workflows/itests.yml
  .github/workflows/itests_race.yml
Labels: github_actions

#1567 Bump golang.org/x/net from 0.30.0 to 0.33.0
  go.mod
  go.sum
Labels: dependencies, go

#1547 New network connection
  .mockery.yaml
  go.mod
  go.sum
  itests/clients/grpc_client.go
  itests/clients/net_client.go
  itests/clients/node_client.go
  itests/clients/universal_client.go
  itests/fixtures/base_fixtures.go
  itests/net/connection.go
  itests/utilities/common.go
  pkg/execution/taskgroup.go
  pkg/execution/taskgroup_test.go
  pkg/networking/address.go
  pkg/networking/configuration.go
  pkg/networking/handler.go
  pkg/networking/logging.go
  pkg/networking/mocks/handler.go
  pkg/networking/mocks/header.go
  pkg/networking/mocks/protocol.go
  pkg/networking/network.go
  pkg/networking/protocol.go
  pkg/networking/session.go
  pkg/networking/session_test.go
  pkg/networking/timers.go
  pkg/p2p/conn/conn.go
  pkg/proto/microblock.go
  pkg/proto/proto.go
  pkg/ride/math/math_test.go
  pkg/util/common/util.go
Labels: enhancement
