Repository wavesplatform/gowaves, pull requests merged in 2025-02, with the labels that each got.

#1604 Deprecated linter "tenv" replaced with "usetesting".
  .github/workflows/go.yml
  .golangci-strict.yml
Labels: enhancement

#1605 Update Go version to 1.23.
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy_node.yml
  .github/workflows/go.yml
  .github/workflows/itests.yml
  .github/workflows/itests_race.yml
  .github/workflows/security.yml
  README.md
  go.mod
Labels: enhancement

#1609 Update Go version to 1.24 in 'deploy_node' workflow.
  .github/workflows/deploy_node.yml
Labels: github_actions

#1607 Session interfaces update
  .mockery.yaml
  itests/clients/net_client.go
  pkg/consensus/blocks_validation.go
  pkg/networking/configuration.go
  pkg/networking/handler.go
  pkg/networking/mocks/handler.go
  pkg/networking/mocks/header.go
  pkg/networking/mocks/protocol.go
  pkg/networking/protocol.go
  pkg/networking/session.go
  pkg/networking/session_test.go
  pkg/node/actions_by_type.go
  pkg/node/fsm/fsm_common.go
  pkg/node/fsm/halt_state.go
  pkg/node/fsm/idle_state.go
  pkg/node/fsm/ng/inv_request.go
  pkg/node/fsm/ng/inv_request_test.go
  pkg/node/fsm/ng_state.go
  pkg/node/fsm/persist_state.go
  pkg/node/fsm/sync_state.go
  pkg/node/fsm/wait_micro_snapshot.go
  pkg/node/fsm/wait_snapshot_state.go
  pkg/p2p/peer/extension/extension.go
  pkg/proto/block.go
  pkg/proto/microblock.go
  pkg/proto/microblock_test.go
  pkg/proto/payloads.go
  pkg/proto/proto.go
  pkg/proto/proto_test.go
  pkg/proto/types.go
Labels: enhancement

#1615 Fixed incorrect error usage in error message.
  itests/init_internal_test.go
Labels: bug

#1616 Lost escape sequence for back slash added to compiler.
  pkg/ride/compiler/ast_parser.go
  pkg/ride/compiler/ast_parser_test.go
Labels: bug
